Appending mangledNameHash to AstNode identifier.
Ericsson/CodeCompass pull request #438
Opened 2020-08-17 15:27 UTC by intjftw

Fixes #436 
The problem was that in 0e85d45b3b94c8289ba4097213570be8d4f0fb0d appending `mangledName` was deleted from `createIdentifier`. This resulted in identifiers not being unique, thus the database overwrote certain records in the `CppAstNode` table.

2020-08-17 19:32 UTC, intjftw commented
@bruntib The CI fails on `CppParserTest.Record` which was modified in #420 :
```cpp
case -1: 
          EXPECT_TRUE(
            // Compiler generated assignment operator return value.
            n.astType == model::CppAstNode::AstType::ReturnTypeLoc ||
            // TODO: What's this? Maybe a compiler generated copy constructor
            // parameter's type? Then why isn't this a ParameterTypeLoc?
            n.astType == model::CppAstNode::AstType::TypeLocation);
          break;
```
That is kind of a weird TODO. The only change was switching `ParameterTypeLoc` to `ReturnTypeLoc` in the first comparison. If I write it back to `ParameterTypeLoc`, the test passes. Why was this change made? Can I write it back to the original?

2020-08-18 16:02 UTC, bruntib commented
Yes, please, write it back to the original. I also had some trouble with determining what exactly that node is. But even if we use `ParameterTypeLoc` then a `ReturnTypeLoc` will be missing for the return type of the compiler generated assignment operator. Please, leave some TODO comment, because this question needs some more investigation.

2020-08-18 21:24 UTC, bruntib requested changes

2020-08-18 21:24 UTC, bruntib commented on plugins/cpp/test/src/cppparsertest.cpp
> +            // a condition is correct. But maybe not.
```suggestion
            // TODO: investigate the type of this. It is possibly the parameter of a
            // compiler generated copy constructor or assignment operator.
            // The type should also be visible as a return type of the compiler generated
            // assignment operator.
```

2020-08-18 22:00 UTC, mcserep approved these changes

2020-08-19 09:12 UTC, merged