rename CppType to CppRecord
Ericsson/CodeCompass pull request #468
Opened 2020-09-18 10:25 UTC by rk717

Fixes #454

2020-09-18 10:26 UTC, bruntib requested changes

2020-09-18 10:26 UTC, bruntib commented on plugins/cpp/CMakeLists.txt
> +#add_subdirectory(test)
Please, don't comment C++ tests out.

2020-09-18 12:42 UTC, mcserep approved these changes
With @bruntib 's comment applied.

2020-09-18 18:10 UTC, bruntib requested changes

2020-09-18 18:10 UTC, bruntib commented on plugins/cpp/parser/src/clangastvisitor.h
> + *e corresponding Traverse... function.
I think this character addition was accidental.

2020-09-22 17:58 UTC, bruntib approved these changes

2020-09-22 17:58 UTC, merged