change invalid connectionstring to valid
Ericsson/CodeCompass pull request #489
Opened 2020-11-10 16:48 UTC by matebelenyesi

Az idézőjelek közé tett adatbázisnevet nem fogadta el, így maradtam a kötőjelek alsóvonásra cserélésénél a connectionstringben.

2020-11-17 21:13 UTC, intjftw requested changes
The changes should be put into _util/src/dbutil.cpp_

2020-11-25 13:45 UTC, mcserep requested changes
I have checked and ODB automatically convert identifiers to *quoted identifier* correctly. (@bruntib already made a remark on one of our previous meetings that there is no issue with our database table names containing uppercase letters. Only the database name raises an error.)

> There is a second kind of identifier: the *delimited identifier* or *quoted identifier*. It is formed by enclosing an arbitrary sequence of characters in double-quotes ("). A delimited identifier is always an identifier, never a key word. So "select" could be used to refer to a column or table named “select”, whereas an unquoted select would be taken as a key word and would therefore provoke a parse error when used where a table or column name is expected. The example can be written with quoted identifiers like this:
> 
> ```
> UPDATE "my_table" SET "a" = 5;
> ```

The issue is with the database creation, which we perform through a native SQL script. Here, the database name is not enclosed between double-quotes:
https://github.com/Ericsson/CodeCompass/blob/1097e5ce0519278dffe44c97e57ed4120d96e2e7/util/src/dbutil.cpp#L175-L179

Fixing it like this solves the original issue:
```cpp
std::string createCmd = "CREATE DATABASE \"" + dbName_ + "\""
  + " ENCODING = 'SQL_ASCII'"
  + " LC_CTYPE='C'"
  + " LC_COLLATE='C'"
  + " TEMPLATE template0;";
```

2020-12-02 13:09 UTC, mcserep approved these changes
Seems good. The commits shall be squashed before merge.

2020-12-02 15:59 UTC, merged

2020-12-02 16:01 UTC, mcserep commented
@matebelenyesi I advise do not create a pull request from the *master* branch of your fork, instead create a new branch.
Now there will be a conflict between Ericsson's *master* and your *master*, and basically you will have to force overwrite your own *master* branch to get them in sync again.