Checking if the result of a query or query_one function is not empty or nullptr
Ericsson/CodeCompass pull request #499
Opened 2020-12-16 17:59 UTC by matebelenyesi

2021-01-09 23:34 UTC, mcserep requested changes
Looks good to me. Since these cases should not occur, maybe add some warning messages to the output, so we can easily identify them later?

2021-01-09 23:34 UTC, mcserep commented on plugins/cpp/service/src/cppservice.cpp
> +      return;
Should be joined with the following check.

2021-01-10 19:40 UTC, zporky commented on plugins/cpp/service/src/cppservice.cpp
> +            nodes.insert(nodes.end(), result.begin(), result.end());
Yes, it is ok to v.insert( v.end(), ...) 
Moreover, if we are about to insert the first element to the vector than we have an empty vector. So this fix may deny us to insert one (or more) elements.

2021-02-13 17:49 UTC, mcserep approved these changes
Fixed the requested changes in bc22f919d564e1319a58044c87ff367ef00a148a.

2021-02-13 18:05 UTC, merged