Efferent coupling of types
Ericsson/CodeCompass pull request #711
Opened 2024-02-18 09:06 UTC by intjftw

This PR solves #673. I'd like to include multiple related tasks, hence the WIP label.

- [ ] Efferent coupling at type level.
- [ ] Refactoring of the C++ metrics plugin: organize metrics calculating functions into separate source files.
- [ ] Test cases for efferent coupling.

2024-04-08 22:56 UTC, mcserep requested changes
Currently this metric calculates the number of aggregated types for each type. Shouldn't inheritance or e.g. function parameter types be considered as well? (Question, should be discussed.)

2024-04-08 22:56 UTC, mcserep commented on plugins/cpp_metrics/parser/src/cppmetricsparser.cpp
> +#include "efferent.h"
Incorrect inclusion order. Please refer to the [coding conventions](https://github.com/Ericsson/CodeCompass/blob/master/doc/coding_conventions.md#headers).

2024-04-08 22:56 UTC, mcserep commented on plugins/cpp_metrics/parser/CMakeLists.txt
> +  src/efferent.cpp
`efferent.h` should also be added here, so CMake can recognize that in case the header file changes, recompilation of the target is required.

2024-07-15 08:39 UTC, intjftw commented
I complemented the calculation with inherited types, member function parameter types and member function local variable types, aside from the already calculated member field types.
I also found and fixed a bug in the C++ metrics service: the first found metric was not returned for any AST node in `getCppAstNodeMetricsDetailedForPath`.
Tests are TBA.

2024-08-30 10:41 UTC, merged