Implementation of C++ metrics parallelization
Ericsson/CodeCompass pull request #734
Opened 2024-04-12 11:33 UTC by dbukki

Fixes #733

Added parallelization support to the C++ metrics parser plugin:
- Using `getFilterPathsQuery`, we can now perform the same check as what `cc::util::isRootedUnderAnyOf` used to do, but on the ODB-side. This is good because:
  - The number of records retrieved for manual processing by the client's handler is now drastically reduced.
  - The `filePath` members can now be removed from views that only needed them for this purpose. This further reduces the amount of data needed to be transferred per record as well.
- The `parallelCalcMetric` method of the metrics parser now serves as the backbone of all parallel computations.
- Existing metrics have been refactored to perform their outermost loop using the new parallelization mechanism.

Further considerations:
- [ ] Buffering: Preload all records to already know the size on startup. (This is a memory overhead, but it might be worth it.)
- [ ] Progress reporting: Building on the idea of buffering, report the current progress of each metric onto the log to increase interactivity. (Reporting at regular intervals in time and/or in steps.)
- [ ] Caching & Flushing: Collect all computed metrics into a single shared thread-safe container and persist everything at once at the end. This could eliminate the "one transaction for each worker" phenomenon currently observed. (Depending on the size of the overhead of opening and closing transactions, this could potentially give us a speed boost.)

2024-06-04 06:59 UTC, mcserep commented
For some reason the diff contains several changes from unrelated PRs, which were already merged. This makes quite hard to review this PR, and the changes should be rebased to `master`.

2024-06-17 05:51 UTC, mcserep commented
> For some reason the diff contains several changes from unrelated PRs, which were already merged. This makes quite hard to review this PR, and the changes should be rebased to `master`.

Any insights on this @dbukki? Could you refactor this PR to `master`? I would love to merge this, but it is quite hard to review it like this.

2024-06-17 17:56 UTC, dbukki commented
> Any insights on this @dbukki? Could you refactor this PR to `master`? I would love to merge this, but it is quite hard to review it like this.

Sorry for not noticing your comment earlier. My branches must have been out of sync by the time I rebased this branch onto my latest version of master to add the parallelization of bumpy road. The funky diff behavior is probably a result of that. I synced my fork, the diff seems alright now.

2024-06-17 21:37 UTC, mcserep requested changes

2024-06-17 21:37 UTC, mcserep commented on plugins/cpp_metrics/parser/include/cppmetricsparser/cppmetricsparser.h
> +odb::query<TQueryParam> getFilterPathsQuery(
This method looks quite independent from C++ metrics and should better be place in `dbutil`.

2024-06-17 21:37 UTC, mcserep commented on plugins/cpp_metrics/parser/src/cppmetricsparser.cpp
> +    _threadCount * 25,// number of jobs; adjust for granularity
How were these magic numbers decided?

2024-06-17 22:46 UTC, mcserep commented on plugins/cpp_metrics/parser/include/cppmetricsparser/cppmetricsparser.h
> +odb::query<TQueryParam> getFilterPathsQuery(
Refactored in 958d418e2861963e68475189fea64b54bd80f9ef.

2024-06-17 22:46 UTC, mcserep commented on plugins/cpp_metrics/parser/src/cppmetricsparser.cpp
> +    _threadCount * 25,// number of jobs; adjust for granularity
Extracted them at least to const members. See fc86a64c0fa4e4299814b9d48a98378c00522309.

2024-06-17 22:46 UTC, mcserep approved these changes

2024-06-17 22:53 UTC, merged