Added calculation for afferent coupling of types
Ericsson/CodeCompass pull request #757
Opened 2024-07-01 10:10 UTC by kmkristof

2024-07-01 13:49 UTC, mcserep commented
@intjftw Since you have worked on efferent coupling in #711, I suggest you to review it, when this PR will be ready.

2024-07-01 13:55 UTC, mcserep commented
@kmkristof Since the development of this new metric was started after *Implementation of C++ metrics parallelization* (see #734) was merged, I suggest to implement this metric with multithread computation on the first attempt, based on the already implemented pattern.

We can consider this task as https://github.com/Ericsson/CodeCompass/labels/Level%3A%20Intermediate%20%283%29 with this added complexity.

2024-07-05 14:16 UTC, intjftw requested changes

2024-07-05 14:16 UTC, intjftw commented on plugins/cpp_metrics/parser/src/cppmetricsparser.cpp
> +      }
My current solution is not complete. This coupling is not only defined by member fields but also by function parameters, inheritance relations etc. Please complement this calculation accordingly.

2024-07-08 22:26 UTC, intjftw requested changes
Testing with TinyXML2, the records in the db contain 0 for the AST node ID for afferent coupling. Another issue is that all afferent coupling records are persisted multiple times (or at least I think I'm discovering a pattern in the data, but the same series of stored metrics seem to be duplicated several times). Also, the afferent metrics are not present in the service component.

2025-03-04 09:05 UTC, mcserep commented
Superseded by #780.

2025-03-04 09:05 UTC, closed without merging